IMPORT Athlete360, STD;

gpsdata := Athlete360.files_stg.MSOCgps_stgfile;

Layout := Athlete360.Layouts.MSOCgpsNUM_stg;

gpsNUMdata := Project(gpsdata,transform({RECORDOF(layout)},
																				SELF.FOR := IF(Left.Position = 'FOR', 1, 0);
																				SELF.CM := IF(Left.Position = 'CM', 1, IF(Left.Position = 'CAM', 1, IF(Left.Position = 'CDM', 1, 0)));
																				SELF.W := IF(Left.Position = 'W', 1, IF(Left.Position = 'WM', 1, 0));
																				SELF.CB := IF(Left.Position = 'CB', 1, IF(Left.Position = 'FB', 1, 0));
																				SELF.OB := IF(Left.Position = 'OB', 1, IF(Left.Position = 'WB', 1, 0));
																				SELF.GK := IF(Left.Position = 'GK', 1, 0);
																				SELF.DayNum := left.daynum;
																				SELF.Drillnum := left.drillnum;
																				SELF.Session1 := IF(Left.Sessiontype = 'Session 1', 1, 0);
																				SELF.Session2 := IF(Left.Sessiontype = 'Session 2', 1, 0);
																				SELF.id := COUNTER;
																				SELF.athid := Left.athleteid;
																				SELF.Impacts := (DECIMAL5_2)Left.Impacts;
																				SELF.Impactsz1 := (DECIMAL5_2)Left.Impactsz1;
																				SELF.Impactsz2 := (DECIMAL5_2)Left.Impactsz2;
																				SELF.Impactsz3 := (DECIMAL5_2)Left.Impactsz3;
																				SELF.Impactsz4 := (DECIMAL5_2)Left.Impactsz4;
																				SELF.Impactsz5 := (DECIMAL5_2)Left.Impactsz5;
																				SELF.Impactsz6 := (DECIMAL5_2)Left.Impactsz6;
																				SELF.Accelerations := (DECIMAL5_2)Left.Accelerations;
																				SELF.Accelerationsz1 := (DECIMAL5_2)Left.Accelerationsz1;
																				SELF.Accelerationsz2 := (DECIMAL5_2)Left.Accelerationsz2;
																				SELF.Accelerationsz3 := (DECIMAL5_2)Left.Accelerationsz3;
																				SELF.Accelerationsz4 := (DECIMAL5_2)Left.Accelerationsz4;
																				SELF.Accelerationsz5 := (DECIMAL5_2)Left.Accelerationsz5;
																				SELF.Accelerationsz6 := (DECIMAL5_2)Left.Accelerationsz6;
																				SELF.Decelerations := (DECIMAL5_2)Left.Decelerations;
																				SELF.Decelerationsz1 := (DECIMAL5_2)Left.Decelerationsz1;
																				SELF.Decelerationsz2 := (DECIMAL5_2)Left.Decelerationsz2;
																				SELF.Decelerationsz3 := (DECIMAL5_2)Left.Decelerationsz3;
																				SELF.Decelerationsz4 := (DECIMAL5_2)Left.Decelerationsz4;
																				SELF.Decelerationsz5 := (DECIMAL5_2)Left.Decelerationsz5;
																				SELF.Decelerationsz6 := (DECIMAL5_2)Left.Decelerationsz6;
																				SELF.highintensityburstnum := (DECIMAL5_2)Left.highintensityburstnum;
																				SELF.highintensityburstdur := (DECIMAL5_2)Left.highintensityburstdur;
																				SELF.Drillstarttime := (DECIMAL5_2)Left.Drillstarttime;
																				SELF.Drilltotaltime := (DECIMAL5_2)Left.Drilltotaltime;
																				SELF.Drilldistance := (DECIMAL10_5)Left.Drilldistance;
																				SELF.Distancepermin := (DECIMAL5_2)Left.Distancepermin;
																				SELF.Highspeeddistance := (DECIMAL5_2)Left.Highspeeddistance;
																				SELF.HighspeeddistanceR := (DECIMAL5_2)Left.HighspeeddistanceR;
																				SELF.AverageHR := (DECIMAL5_2)Left.AverageHR;
																				SELF.timeabove85 := (DECIMAL5_2)Left.timeabove85;
																				SELF.HRexertion := (DECIMAL5_2)Left.HRexertion;
																				SELF.MaxHR := (DECIMAL5_2)Left.MaxHR;
																				SELF.HRz1 := (DECIMAL5_2)Left.HRz1;
																				SELF.sprints := (DECIMAL5_2)Left.sprints;
																				SELF.Dynamicstressloadtotal := (DECIMAL5_2)Left.Dynamicstressloadtotal;
																				SELF.Dynamicstressloadz1 := (DECIMAL5_2)Left.Dynamicstressloadz1;
																				SELF.Dynamicstressloadz2 := (DECIMAL5_2)Left.Dynamicstressloadz2;
																				SELF.Dynamicstressloadz3 := (DECIMAL5_2)Left.Dynamicstressloadz3;
																				SELF.Dynamicstressloadz4 := (DECIMAL5_2)Left.Dynamicstressloadz4;
																				SELF.Dynamicstressloadz5 := (DECIMAL5_2)Left.Dynamicstressloadz5;
																				SELF.Dynamicstressloadz6 := (DECIMAL5_2)Left.Dynamicstressloadz6;
																				SELF.totalloading := (DECIMAL5_2)Left.totalloading;
																				SELF.Maxspeed := (DECIMAL5_2)Left.Maxspeed;
																				SELF.Distancez6 := (DECIMAL5_2)Left.Distancez6;
																				SELF.Distancez6R := (DECIMAL5_2)Left.Distancez6R;
																				SELF.HSRpermin := (DECIMAL5_2)Left.HSRpermin;
																				SELF.HSRperminR := (DECIMAL5_2)Left.HSRperminR;
																				SELF.metabolicdis := (DECIMAL10_5)Left.metabolicdis;
																				SELF.explosivedis := (DECIMAL10_5)Left.explosivedis;
																				SELF.Accelerationimp := (DECIMAL5_2)Left.Accelerationimp;
																				SELF.Accelerationsdisz1 := (DECIMAL5_2)Left.Accelerationsdisz1;
																				SELF.Accelerationsdisz2 := (DECIMAL5_2)Left.Accelerationsdisz2;
																				SELF.Accelerationsdisz3 := (DECIMAL5_2)Left.Accelerationsdisz3;
																				SELF.Accelerationsdisz4 := (DECIMAL5_2)Left.Accelerationsdisz4;
																				SELF.Accelerationsdisz5 := (DECIMAL5_2)Left.Accelerationsdisz5;
																				SELF.Accelerationsdisz6 := (DECIMAL5_2)Left.Accelerationsdisz6;
																				SELF.Decelerationsdisz1 := (DECIMAL5_2)Left.Decelerationsdisz1;
																				SELF.Decelerationsdisz2 := (DECIMAL5_2)Left.Decelerationsdisz2;
																				SELF.Decelerationsdisz3 := (DECIMAL5_2)Left.Decelerationsdisz3;
																				SELF.Decelerationsdisz4 := (DECIMAL5_2)Left.Decelerationsdisz4;
																				SELF.Decelerationsdisz5 := (DECIMAL5_2)Left.Decelerationsdisz5;
																				SELF.Decelerationsdisz6 := (DECIMAL5_2)Left.Decelerationsdisz6;
																				SELF.gamedaycount := Left.gamedaycount;
																				SELF.wuid := workunit;
																				SELF := LEFT
																				)
																				);
																				
																				
EXPORT build_MSOCgpsNUM := Athlete360.util.fn_promote_ds(Athlete360.util.constants.stg_prefix,  Athlete360.util.constants.MSOCgpsNUM_name, gpsNUMdata);